[package]
name = "io"
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
publish.workspace = true
readme.workspace = true
version.workspace = true

[build-dependencies]
bindgen = { version = "0.65.1" }

[dependencies]

[features]
# default = ["dep:bindgen", "ncurses"]
# ncurses = []